### ISSUE TITLE
disable tag builds for prereleases

### ISSUE THREAD

**Issue by travi** [travi/travis-scaffolder-javascript#8]
```yaml
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
```

is too specific to catch `vx.x.x-beta` and similar
